name: Docs

on:
  workflow_call:

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Markdown Lint
        uses: DavidAnson/markdownlint-cli2-action@v18
        with:
          config: .markdownlint-cli2.yaml
          globs: |
            **/*.md
